filter-by-commitish: true
commitish: beta
# include-prereleases: true
name-template: "v$RESOLVED_VERSION-beta"
tag-template: "v$RESOLVED_VERSION-beta"
version-template: "$COMPLETE"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  **Release Engineer:** $CONTRIBUTORS
  **Previous Release:** $PREVIOUS_TAG
  ## What's Changed
  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
  