name: Publish beta development tag

on:
  pull_request:
    branches:
      - beta

jobs:
  read-package-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read package.json
        run: |
          version=$(cat package.json | grep -oP '(?<="version": ")[^"]+')
          echo "Version: $version"