name: Publish beta development tag

on:
  pull_request:
    branches:
      - beta

jobs:
  read-package-json:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-json.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read package.json
        id: read-json
        run: |
          echo "::set-output name=version::$(cat package.json | grep -oP '(?<="version": ")[^"]+')"
          echo "Version: ${{ steps.read-json.outputs.version }}"

      - name: Append commit SHA
        run: |
          github_sha="${{ github.sha }}"
          trimmed_sha="${github_sha::5}"
          version="${{ steps.read-json.outputs.version }}.${trimmed_sha}"
          echo "Version with commit SHA: $version"