name: Publish beta development tag

on:
  pull_request:
    branches:
      - beta

jobs:
  read-package-json:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-json.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read package.json
        id: read-json
        run: |
          echo "::set-output name=version::$(cat package.json | grep -oP '(?<="version": ")[^"]+')"
          echo "Version: ${{ steps.read-json.outputs.version }}"

      - name: Determine new version
        id: determine-version
        run: |
          version="${{ steps.read-json.outputs.version }}"
          
          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            version_parts=(${version//./ })
            middle_part=$((version_parts[1] + 1))
            new_version="${version_parts[0]}.${middle_part}.${version_parts[2]}"
          elif [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta\.[A-Za-z0-9]+$ ]]; then
            new_version="${version%-*}"
            echo "$new_version"
          else
            echo "Invalid version format, needs to be dd.dd.dd OR dd.dd.dd-beta.{GITHUB_SHA}"
            exit 1
          fi
          
          echo "::set-output name=new_version::$new_version"

      - name: Publish beta development tag
        run: |
          github_sha="${{ github.sha }}"
          trimmed_sha="${github_sha::5}"

          new_version="${{ steps.determine-version.outputs.new_version }}-beta.${trimmed_sha}"
          echo "New version: $new_version"
          # Add your actions to publish the tag or perform any other necessary steps with the new version