name: Lighthouse CI Action

on: push
  

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating Check Run
        id: create_run
        run: |
          RESPONSE=$(curl https://catfact.ninja/fact |
          jq '.')
          FACT=$(echo $RESPONSE | jq '.fact')
          LENGTH=$(echo $RESPONSE | jq '.length')

          # echo $RESPONSE_PROCESSED |
          echo "::set-output name=FACT::$FACT"
          echo "::set-output name=LENGTH::$LENGTH"

      - name: Print
        run: |
          echo "${{toJSON(steps.create_run.outputs)}}"
      - name: t
        run: env