name: Lighthouse CI Action

on: push
  

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creating Check Run
        id: create_run
        run: |
          RESPONSE=$(curl https://catfact.ninja/fact) |
          # RESPONSE_PROCESSED=$(fromJSON($RESPONSE)) |
          # echo $RESPONSE_PROCESSED |
          echo "::set-output name=RESPONSE::${{fromJSON($RESPONSE)}}"
      - name: Print
        run: |
          echo "${{toJSON(steps.create_run.outputs)}}"
      - name: t
        run: env