name: Pull Request Action
on: push

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Extract branch name
        shell: bash
        run: echo ${GITHUB_REF##*/}
        id: extract_branch
      - name: create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr create -B master -H ${GITHUB_REF##*/}
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}