name: Pull Request Action
on: push

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Extract branch name
        shell: bash
        run: echo ${GITHUB_REF}
        id: extract_branch
      - name: Find jira number
        id: find-jira-number
        shell: bash
        run: echo "JIRA_NUMBER=$(echo "$GITHUB_REF" | grep -o -P '([A-Za-z][A-Za-z0-9]+-[0-9]+)')" >> $GITHUB_OUTPUT
      - name: Print jira
        shell: bash
        run: |
          echo ${{steps.find-jira-number.outputs.JIRA_NUMBER}}


      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_REF
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName)
          echo $prs
          for i in "${prs[@]}"
            do
             echo $i

              # echo $(echo $i | jq -r '.baseRefName')
              # echo $(i_headRefName == $GITHUB_REF)
              # if(i_baseRefName == "master" && i_headRefName == $GITHUB_REF) then
              #   echo "present"
              #   echo "skip=true" >> "$GITHUB_OUTPUT"
              # fi
          done


      - name: create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        if: '!steps.check.outputs.skip'
        run: gh pr create -B master -H ${GITHUB_REF}  --draft --title '${{steps.find-jira-number.outputs.JIRA_NUMBER}} | Draft PR' --body-file .github/pull_request_template.md
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


