name: Pull Request Action
on: push

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Find jira number
        id: find-jira-number
        shell: bash
        run: echo "JIRA_NUMBER=$(echo "$GITHUB_REF" | grep -o -P '([A-Za-z][A-Za-z0-9]+-[0-9]+)')" >> $GITHUB_OUTPUT
      - name: Get formatted branch name
        id: formatted-branch-name
        shell: bash
        run: |
          formattedName=$(echo $GITHUB_REF | grep -o -P '(?!.*\/).+' | tr '-' ' ' | tr '_' ' ')
          echo "FORMATTED_NAME=$formattedName" >> $GITHUB_OUTPUT
      - name: Check if PR exists
        id: pr-exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_REF"
          prs=$(gh pr list \
              --repo $GITHUB_REPOSITORY \
              --base "master" \
              --head ${GITHUB_REF#refs/heads/} \
              --json baseRefName,headRefName )

          echo "$prs"

          if [ "$prs" != [] ]; then
            echo "present"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        if: '!steps.pr-exists.outputs.skip'
        run: |
          jiraNumber="${{steps.find-jira-number.outputs.JIRA_NUMBER}}"
          finalTitle=""
          echo "$jiraNumber"
          if [ -n "$jiraNumber" ]; then
            echo "string not empty"
            finalTitle+="$jiraNumber | "
            echo "$finalTitle"
          fi
          formattedTitle="${{steps.formatted-branch-name.outputs.FORMATTED_NAME}}"
          finalTitle+="$formattedTitle"
          gh pr create -B master -H ${GITHUB_REF} --draft --title "$finalTitle" --body-file .github/pull_request_template.md


