name: On Release

on: push
  

jobs:
  on-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print
        run: |
          echo "${{toJSON(github.event)}}"
      - name: t
        run: env