# On a release being published, checkout the main branch, create a new file, commit that file, and push it to main

name: Publish on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout ${{ github.head_ref }}
      - name: Update package.json version
        run: |
          tag_name=${{ github.event.release.tag_name }}
          # regex removes the leading 'v' from the tag name
          raw_version_number=${incremented_version#"v"}
          jq --arg raw_version_number "$raw_version_number" '.version = $raw_version_number' package.json > package.json.tmp && mv package.json.tmp package.json
          cat package.json

          git add package.json
          git commit -m "Incrementing package.json to $raw_version_number in preparation for eventual merge"
          git push
      - name: Create and push new git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_version=${{ github.event.release.tag_name }}
          git tag $new_version -m "Published from release: ${{github.event.release.name}}"
          git push origin HEAD
          git push --tags

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@red-digital'
      - run: npm i
      - run: echo "npm publish --tag"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
