name: pr-validate

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  pr-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint JS
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Check branch name
        run: |
          # check if the branch name is prefixed by one of the strings in an array
          arr=('feature/' 'bugfix/' 'hotfix/' 'maintenance/' 'techdebt/')

          # check if the branch starts with one of the strings in the array
          if [[ ! " ${{ github.head_ref }} " =~ ^(${arr[@]}) ]]; then
            echo "Branch name must be prefixed by one of the following: ${arr[@]}"
            exit 1
          fi
