# On a release being published this will:
# 1. Update the package.json version to match the release tag
# 2. Publish the new version to npm

name: Publish Package Version on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout ${{ github.head_ref }}
      - name: Update package.json version
        id: update-package-json
        run: |
          tag_name=${{ github.event.release.tag_name }}
          # regex removes the leading 'v' from the tag name
          raw_version_number=${tag_name#"v"}
          echo "raw_version_number: $raw_version_number"
          jq --arg raw_version_number "$raw_version_number" '.version = $raw_version_number' package.json > package.json.tmp && mv package.json.tmp package.json
          cat package.json

          branch_name="update-package-json-$raw_version_number"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

          git checkout -b $branch_name
          git add package.json
          git commit -m "Updating package.json to $raw_version_number from release"
          git push -u origin $branch_name
      - name: create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create -B main -H ${GITHUB_REF} --title "${{github.event.release.tag_name}}" --body "Updating package.json to $raw_version_number from release"

      # # Setup .npmrc file to publish to GitHub Packages
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://npm.pkg.github.com'
      #     # Defaults to the user or organization that owns the workflow file
      #     scope: '@red-digital'
      # - run: npm i
      # - run: echo "npm publish --tag"
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
