
name: Release Drafter Beta

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - beta

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "beta"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: relase-drafter-beta.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
